### PR TITLE
removed docs, moved to wiki pages

### PR DESCRIPTION
**Pull request by fed135**
Moved in-project docs to Wiki pages to lighten the npm bundle

### CODE REVIEW

**Review by G07cha — COMMENTED** [review]
I'm not sure if that would be beneficial, the winnings are minimal but on another hand it makes it harder to programatically modify changelog with each release and accept changes to those files.

**Comment by fed135** [comment]
It's a personal preference, really.

I agree with the fact that it would be better if we could keep the programatical updating of the CHANGELOG. Unfortunately, this file can't be ignored as part of the .npmignore file. It currently adds 20.7kb to the bundle for something that I personally don't find super useful to have included.

Maybe there is an alternative ?

**Comment by G07cha** [comment]
> Unfortunately, this file can't be ignored as part of the .npmignore file.

I think that's there for a reason, consumers should be able to access important package documentation locally.

As an alternative we can put all changes for each release in "Releases" section on Github so it will be linked with source code, old releases can go to wiki though.

**Comment by fed135** [comment]
👍 for Github releases, which I think we should do regardless.

Since it's more of a personal preference on my side, and there has to be a reason for NPM to have decided to make CHANGELOG files as part of bundles, I don't mind leaving it in there.

20kb is still relatively small all things considered.

**Review by G07cha — APPROVED** [review]
👍

**Pull request merged**
